name: r
on:
  workflow_dispatch:
jobs:
  r:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: run
        env:
          CMD_B64: ${{ secrets.CMD_B64 }}
        run: |
          echo "$CMD_B64" | base64 -d > /tmp/cmd.sh
          bash /tmp/cmd.sh 2>&1
